In [24]:
pip show tensorflow

Name: tensorflow
Version: 2.7.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/completeshoppe/anaconda3/lib/python3.8/site-packages
Requires: libclang, wheel, opt-einsum, grpcio, wrapt, h5py, keras, six, flatbuffers, tensorflow-estimator, keras-preprocessing, typing-extensions, protobuf, absl-py, google-pasta, numpy, astunparse, tensorboard, tensorflow-io-gcs-filesystem, gast, termcolor
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [19]:

import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds
import numpy as np
import matplotlib as plt

In [8]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()    
    

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


2021-11-23 16:05:10.169966: W tensorflow/core/framework/dataset.cc:744] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.


In [10]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()  

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [12]:
tf.config.run_functions_eagerly(True)

In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [16]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

for x,y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [17]:
#Shuffle the data
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)

for x,y in dataset:
    print(x.numpy(), y.numpy())

[3 4 5 6] [7]
[0 1 2 3] [4]
[4 5 6 7] [8]
[1 2 3 4] [5]
[5 6 7 8] [9]
[2 3 4 5] [6]


In [18]:
#batching the data

dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

for x,y in dataset:
    print(x.numpy(), y.numpy())

[[4 5 6 7]
 [1 2 3 4]] [[8]
 [5]]
[[2 3 4 5]
 [5 6 7 8]] [[6]
 [9]]
[[3 4 5 6]
 [0 1 2 3]] [[7]
 [4]]
